import { ClearPosts } from "./application/posts/ClearPosts";
import { CreatePost } from "./application/posts/CreatePost";
import { DeletePost } from "./application/posts/DeletePost";
import { GetPost } from "./application/posts/GetPost";
import { ListPosts } from "./application/posts/ListPosts";
import { SearchPost } from "./application/posts/SearchPost";
import { PostController } from "./infra/controller/PostController";
import { MongoAdapter } from "./infra/database/MongoAdapter";
import { Registry } from "./infra/di/DependencyInjection";
import { ExpressAdapter } from "./infra/http/ExpressAdapter";
import { ConsoleLogger } from "./infra/logger/ConsoleLogger";
import { WinstonLogger } from "./infra/logger/WinstonLogger";
import { MemoryPostsRepository } from "./infra/repository/MemoryPostsRepository";
import { MongoPostsRepository } from "./infra/repository/MongoPostsRepository";
import { Settings } from "./infra/settings/Settings";

const httpServer = new ExpressAdapter();
const settings = new Settings();
Registry.getInstance().provide("HttpServer", httpServer);
Registry.getInstance().provide("Settings", settings);
Registry.getInstance().provide("Logger", new WinstonLogger());
// Registry.getInstance().provide("Logger", new ConsoleLogger());
Registry.getInstance().provide("Database", new MongoAdapter());
Registry.getInstance().provide("PostsRepository", new MongoPostsRepository());
// Registry.getInstance().provide("PostsRepository", new MemoryPostsRepository());
Registry.getInstance().provide("CreatePost", new CreatePost());
Registry.getInstance().provide("ClearPosts", new ClearPosts());
Registry.getInstance().provide("DeletePost", new DeletePost());
Registry.getInstance().provide("GetPost", new GetPost());
Registry.getInstance().provide("ListPosts", new ListPosts());
Registry.getInstance().provide("SearchPost", new SearchPost());
Registry.getInstance().provide("PostController", new PostController());
httpServer.listen(settings.port);
